//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DartaChalani
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblChalani
    {
        public int ChalaniNo { get; set; }
        public Nullable<System.DateTime> ChalaniDate { get; set; }
        public string FiscalYear { get; set; }
        public string ReferenceNo { get; set; }
        public string PatraDate { get; set; }
        public string Subject { get; set; }
        public string OfficeName { get; set; }
        public string Bodhartha { get; set; }
        public string File { get; set; }
        public string Remarks { get; set; }
    }
}
